@startuml
User -> (Browser) : 1、打开浏览器

(Browser) -> (系统设置) : 2、访问系统设置

(系统设置) --> (单点登录) : 3、校验是否登录

(单点登录) --> (Browser) : 4、需要登录

(Browser) --> (单点登录) : 5、输入用户名、密码

(单点登录) <--> (用户信息) : 6、校验用户信息

(单点登录) --> (系统设置) : 7、返回token等信息

(系统设置) --> (单点登录) : 8、验证token信息

(单点登录) --> (系统设置) : 9、返回用户信息

(系统设置) --> (Browser) : 10、正常访问

@enduml