@startuml

actor 用户 as User
participant 浏览器 as Browser
participant 单点登录服务 as SSOSvc
participant 权限管理服务 as AuthSvc

User -> Browser : http://ip:8800
Browser -> SSOSvc : /auth/authorize\n判断是否已登录
SSOSvc --> SSOSvc : 未登录，重定向至登录页面
SSOSvc --> Browser : http://ip:8800/#/auth_login
User -> Browser : 输入用户名密码登录
Browser -> SSOSvc : /auth/is_session_valid\n判定当前浏览器是否已有账号登录
SSOSvc --> Browser : 返回是否有账号登录
Browser --> User: 已登录，提示用户已有账号登录
Browser -> SSOSvc : 无账号登录，发起登录请求\n/auth/logins
SSOSvc -> AuthSvc : 根据账号查询用户信息\n/account/user
AuthSvc --> SSOSvc : 返回用户信息
SSOSvc --> SSOSvc : 生成sid和code
SSOSvc --> Browser : 返回sid、code和是否首次登录
Browser --> User : 是首次登录，弹出修改密码框
User -> Browser : 修改密码
Browser -> AuthSvc : 修改密码
AuthSvc --> Browser : 返回修改结果
Browser -> SSOSvc : /auth/check_session
SSOSvc --> Browser : 返回校验session的html
Browser -> SSOSvc : /auth/location
SSOSvc --> Browser : 重定向页面并设置cookie
Browser --> User : 显示用户九宫格页面
Browser -> SSOSvc : /auth/token\n换取token
SSOSvc --> Browser : 返回token等信息
Browser -> SSOSvc : /auth/is_access_token_valid\n校验token是否有效
SSOSvc --> Browser : 返回校验结果

@enduml