@startuml
actor 用户 as User
participant 浏览器 as Browser
participant 子应用1 as App1
participant 子应用2 as App2
participant 单点登录前端 as SSOWeb
participant 单点登录后端 as SSOSvc

group 访问子应用1
User -> Browser :
Browser -> App1 : http://app1:xxxx
App1 -> SSOSvc : 验证用户是否登录
SSOSvc --> SSOSvc : 未登录
SSOSvc --> SSOWeb : 重定向登录页面?redirect_url=http://app1:xxxx
SSOWeb -> SSOSvc : 携带cookie判定是否登录
SSOSvc --> SSOSvc : 验证失败
SSOSvc --> SSOWeb : 需要登录
SSOWeb --> User : 需要登录
User -> SSOWeb : 输入用户名密码登录
SSOWeb -> SSOSvc : 携带用户名密码（登录端，子应用1）验证
SSOSvc --> SSOSvc : 验证成功
SSOSvc --> SSOSvc : 设置cookie
SSOSvc --> SSOSvc : 创建token
SSOSvc --> Browser : 重定向“http://app1:xxxx”，携带token等信息
Browser -> App1 : 子应用1（携带token）
App1 -> SSOSvc : 验证token
SSOSvc --> SSOSvc : 验证成功
SSOSvc --> App1 : 返回相应信息
App1 --> User : 正常访问
end

group 访问子应用2
User -> App2: http://app2:xxxx
App2 -> SSOSvc : 验证是否登录
SSOSvc --> SSOSvc : 未登录
SSOSvc --> SSOWeb : 重定向登录页面?redirect_url=http://app2:xxxx
SSOWeb -> SSOSvc : 携带cookie判定是否登录
SSOSvc --> SSOSvc : 验证成功
SSOSvc --> Browser : 重定向“http://app2:xxxx”，携带token等信息
Browser -> App2 : 子应用2（携带token）
App2 -> SSOSvc : 验证token
SSOSvc --> SSOSvc : 验证成功
SSOSvc --> App2 : 返回相应信息
App2 --> User : 正常访问
end

group 退出登录
User -> App1 : 退出登录
App1 -> SSOSvc : logout?redirect_url=http://app1:xxxx
SSOSvc --> SSOSvc : 销毁token
SSOSvc --> SSOSvc : 清除cookie
SSOSvc --> SSOWeb : 重定向登录页面?redirect_url=http://app1:xxxx
SSOWeb --> User : 需要登录
App2 --> App2 : 检测App1退出登录
App2 --> SSOSvc : 验证token
SSOSvc --> SSOSvc : 验证失败
SSOSvc --> SSOWeb : 重定向登录页面?redirect_url=http://app2:xxxx
SSOWeb --> User : 需要登录
end
@enduml